/**
 * MingCute icon barrel — single import surface for the storefront UI.
 */
export {
  Aiming2Regular,
  AlertRegular,
  ArrowLeftRegular,
  ArrowRightRegular,
  BadgeRegular,
  CheckCircleRegular,
  CheckRegular,
  ClassifyRegular,
  CloseRegular,
  DownRegular,
  DownloadRegular,
  EmptyBoxRegular,
  ExitRegular,
  GiftRegular,
  Home1Regular,
  InformationRegular,
  Loading2Regular,
  MapPinRegular,
  More2Regular,
  NavigationRegular,
  PackageRegular,
  PencilRegular,
  PercentageRegular,
  PlusRegular,
  Refresh1Regular,
  RightRegular,
  SearchRegular,
  Share2Regular,
  ShoppingCart1Regular,
  TagRegular,
  User1Regular,
  SearchRegular as IconSearch,
  CloseRegular as IconClose,
  ArrowLeftRegular as IconChevronLeft,
  DownRegular as IconChevronDown,
  RightRegular as IconChevronRight,
  Loading2Regular as IconLoader,
} from '@mingcute/react/core-regular';

export {
  ClassifyFilled,
  EmptyBoxFilled,
  Home1Filled,
  Refresh1Filled,
  ShoppingCart1Filled,
} from '@mingcute/react/core-filled';
